"use client";

import React, { Suspense, useEffect, useState } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

// --- PAYHERE TYPES ---
interface PayHerePaymentObject {
  sandbox: boolean;
  merchant_id: string;
  return_url: string;
  cancel_url: string;
  notify_url: string;
  order_id: string;
  items: string;
  amount: string | number;
  currency: string;
  hash: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
  address: string;
  city: string;
  country: string;
}

interface PayHere {
  startPayment: (payment: PayHerePaymentObject) => void;
  onCompleted: (orderId: string) => void;
  onDismissed: () => void;
  onError: (error: string) => void;
}

declare const payhere: PayHere;

function CheckoutContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const selectedPackage = searchParams.get("package") || "standard";
  const orderId = searchParams.get("orderId");

  const [userEmail, setUserEmail] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);

  const priceMap: Record<string, { label: string; price: string }> = {
    basic: { label: "Basic Resume Pack", price: "30.00" },
    standard: { label: "Standard Resume Pack", price: "50.00" },
    premium: { label: "Premium Transformation", price: "80.00" },
  };

  const currentSelection =
    priceMap[selectedPackage.toLowerCase()] || priceMap.standard;

  useEffect(() => {
    const fetchUser = async () => {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (user) {
        setUserEmail(user.email || "");
      } else {
        router.push(`/login?package=${selectedPackage}`);
      }
    };
    fetchUser();
  }, [router, selectedPackage]);

  const startPayment = async () => {
    if (typeof payhere === "undefined") {
      alert("Payment gateway is still loading. Please wait a moment.");
      return;
    }

    if (!orderId) {
      alert("Invalid order session. Please go back and try again.");
      return;
    }

    setLoading(true);

    try {
      // 1. Fetch the secure hash from your API route (src/app/api/payhere/hash/route.ts)
      const response = await fetch("/api/payhere/hash", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          orderId: orderId,
          amount: currentSelection.price,
          currency: "USD",
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate secure hash");
      }

      const { hash } = await response.json();

      // 2. Setup the Payment Object
      const payment: PayHerePaymentObject = {
        sandbox: true, // KEEP TRUE FOR TESTING
        merchant_id: "1233959",
        return_url: `${window.location.origin}/dashboard?status=success`,
        cancel_url: `${window.location.origin}/checkout?package=${selectedPackage}&orderId=${orderId}`,
        notify_url: "https://evellacreates.com/api/payhere-webhook",
        order_id: orderId,
        items: currentSelection.label,
        amount: currentSelection.price,
        currency: "USD",
        hash: hash, // The hash generated by your server
        first_name: "Customer",
        last_name: userEmail ? userEmail.split("@")[0] : "Client",
        email: userEmail,
        phone: "0771234567",
        address: "Online Service",
        city: "Colombo",
        country: "Sri Lanka",
      };

      // 3. Define Callback Listeners
      payhere.onCompleted = () => {
        router.push(`/dashboard?package=${selectedPackage}&payment=success`);
      };
      payhere.onDismissed = () => {
        setLoading(false);
        console.log("Payment modal closed by user");
      };
      payhere.onError = (err) => {
        setLoading(false);
        alert("Payment Error: " + err);
      };

      // 4. Trigger the Modal
      payhere.startPayment(payment);
    } catch (err) {
      console.error("Payment error:", err);
      alert(
        "Could not initialize payment. Please check your internet connection.",
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="container py-5 mt-5">
      <div className="row justify-content-center">
        <div className="col-lg-6">
          <div className="card modern-card p-5 text-center shadow-sm border-0">
            <h2 className="fw-bold mb-4">Finalize Your Investment</h2>
            <p className="text-muted mb-5">
              Package: <strong>{currentSelection.label}</strong>
            </p>

            <div className="bg-light p-4 rounded-4 mb-5">
              <div className="d-flex justify-content-between h3 fw-bold mb-0">
                <span>Total:</span>
                <span>${currentSelection.price}</span>
              </div>
            </div>

            <button
              onClick={startPayment}
              className="btn btn-evella-primary btn-lg w-100 py-3 fw-bold shadow-sm mb-3"
              disabled={loading}
            >
              {loading ? "Processing..." : "Invest Now"}
            </button>

            <p className="small text-muted">
              <i className="bi bi-shield-lock me-1"></i> Secure via PayHere
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}

export default function CheckoutPage() {
  return (
    <Suspense
      fallback={
        <div className="container py-5 mt-5 text-center">
          Preparing Checkout...
        </div>
      }
    >
      <CheckoutContent />
    </Suspense>
  );
}
